version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.0
  aws-ecr: circleci/aws-ecr@3.1.0
  kubernetes: circleci/kubernetes@0.3.0
  aws-cli: circleci/aws-cli@0.1

jobs:
  Cluster-demo:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - aws-cli/setup:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-region: $AWS_DEFAULT_REGION
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY_ID
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: Cluster-demo
      - run:
          command: |
            kubectl get services
          name: Cluster-demo
  undeploy-application:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Cluster-demo
        type: string
      aws-region:
        description: |
          us-east-2
        type: string
        default: us-east-2 

workflows:
  deployment:
    jobs:        
      - aws-eks/delete-cluster:
          cluster-name: eks-orb-demo-app-deployment
          aws-region: $AWS_DEFAULT_REGION
          wait: true
          requires:
            - undeploy-application
