version: 2.1

orbs:
    hello: circleci/hello-build@0.0.5
    aws-eks: circleci/aws-eks@0.2.0
    aws-ecr: circleci/aws-ecr@3.1.0
    kubernetes: circleci/kubernetes@0.3.0
    aws-cli: circleci/aws-cli@0.1

jobs:
  Cluster-demo:
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_ID
          
workflows:
    "Hello Workflow":
        jobs:
          - hello/hello-build
          

